@extends('common.layout')

@section('content')
<div class="primary_container">	
	<div class="row">
		<div class="small-12 columns">
			<table>
				<tbody>
				@foreach($invites as $invite)
					<tr>
						
						<td>{{$invite->code}}</td>
						<td>{{$invite->invite_email}}</td>
					</tr>
		   		@endforeach
				</tbody>
			</table>
			<div class='panel'>
				<div class="row">
					<div class="small-12 columns">
						<h4>Add invitation code</h4>
						<p>The code itself will be generated by the system just add the email it should be claimed by</p>

						<form action="{{ action('InviteController@store') }}" method="post" data-abide>{{ csrf_field() }}
						<div class="row">
							<div class="small-8 columns">
								<input type="email" name="invite_email">
							</div>
							<div class="small-4 columns">
								<input class="button" type="submit">
							</div>
						</div>
						</form>
					</div>
				</div>
			</div>

			
		</div>
	</div>
   </div>
@endsection

